# This is a basic workflow to help you get started with Actions

name: Coveralls

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Coveralls GitHub Action
        # You may pin to the exact commit or the version.
        # uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
        uses: coverallsapp/github-action@1.1.3
          
      - name: generate coverage report
        run: |
          npm install
          npm run test:coveralls
        
